version: '3.8'

services:
  backend:
    build: ./home_backend
    container_name: sinhthainhatoi-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    volumes:
      - ./home_backend/upload:/app/upload
      - backend_node_modules:/app/node_modules
    networks:
      - app-network
      
  frontend:
    build: ./home_frontend
    container_name: sinhthainhatoi-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_HOST_URL=http://localhost:4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules:
